{u'addonIDs': [],
 u'amountPaid': u'0.00',
 u'appointmentTypeID': 299489,
 u'calendar': u'How to Manage a Small Law Firm ',
 u'calendarID': 140955,
 u'calendarTimezone': u'America/New_York',
 u'canClientCancel': False,
 u'canClientReschedule': True,
 u'canceled': False,
 u'category': u'',
 u'certificate': None,
 u'classID': None,
 u'confirmationPage': u'https://app.acuityscheduling.com/schedule.php?owner=11403102&action=appt&id%5B%5D=4f778aa7b58f596e9f5a2c08d038e498',
 u'date': u'July 12, 2021',
 u'dateCreated': u'May 13, 2021',
 u'datetime': u'2021-07-12T12:00:00-0400',
 u'datetimeCreated': u'2021-05-13T21:41:47-0500',
 u'duration': u'60',
 u'email': u'ahashim@hashimlawfirm.com',
 u'endTime': u'1:00pm',
 u'firstName': u'Asad',
 u'forms': [{u'id': 1330877,
             u'name': u'UTM attribution tracking',
             u'values': [{u'fieldID': 7300773,
                          u'id': 1886685448,
                          u'name': u'utm_source',
                          u'value': u'sm linktree'},
                         {u'fieldID': 7300775,
                          u'id': 1886685449,
                          u'name': u'utm_medium',
                          u'value': u'social media'},
                         {u'fieldID': 7300777,
                          u'id': 1886685451,
                          u'name': u'utm_campaign',
                          u'value': u'6 Stages Webinar'},
                         {u'fieldID': 7300781,
                          u'id': 1886685452,
                          u'name': u'utm_content',
                          u'value': u'6 Stages Webinar Opt-In'},
                         {u'fieldID': 7300782,
                          u'id': 1886685453,
                          u'name': u'utm_term',
                          u'value': u'null'},
                         {u'fieldID': 7300788,
                          u'id': 1886685455,
                          u'name': u'referring_url',
                          u'value': u'https://go.howtomanageasmalllawfirm.com/6-stages-webinar-confirmation-social/?firstname=Asad&lastname=Hashim&email=ahashim%40hashimlawfirm.com&phone=8579308953&which_best_describes_you=I%E2%80%99m%20stuck%20at%20my%20current%20revenue%20level%20&utm_source=sm%20linktree&utm_medium=social%20media&utm_campaign=6%20Stages%20Webinar&utm_content=6%20Stages%20Webinar%20Opt-In'}]},
            {u'id': 113296,
             u'name': u'What is your biggest frustration in your business?',
             u'values': [{u'fieldID': 390382,
                          u'id': 1886685456,
                          u'name': u'What is your biggest frustration in your business?',
                          u'value': u'Obtaining clients as a new law firm/recent graduate. '},
                         {u'fieldID': 1922746,
                          u'id': 1886685457,
                          u'name': u'Skype Address - Are you calling from outside the US and Canada?',
                          u'value': u''},
                         {u'fieldID': 5749294,
                          u'id': 1886685458,
                          u'name': u'How did you hear about us? ',
                          u'value': u'Social Media/Online Ad'}]}],
 u'formsText': u'Name: Asad Hashim\nPhone: (857) 930-8953\nEmail: ahashim@hashimlawfirm.com\n\nUTM attribution tracking\n============\nutm_source: sm linktree\n\nutm_medium: social media\n\nutm_campaign: 6 Stages Webinar\n\nutm_content: 6 Stages Webinar Opt-In\n\nutm_term: null\n\nreferring_url: https://go.howtomanageasmalllawfirm.com/6-stages-webinar-confirmation-social/?firstname=Asad&lastname=Hashim&email=ahashim%40hashimlawfirm.com&phone=8579308953&which_best_describes_you=I%E2%80%99m%20stuck%20at%20my%20current%20revenue%20level%20&utm_source=sm%20linktree&utm_medium=social%20media&utm_campaign=6%20Stages%20Webinar&utm_content=6%20Stages%20Webinar%20Opt-In\n\n\n\nWhat is your biggest frustration in your business?\n============\nWhat is your biggest frustration in your business?: Obtaining clients as a new law firm/recent graduate. \n\nSkype Address - Are you calling from outside the US and Canada?: \n\nHow did you hear about us? : Social Media/Online Ad\n\n',
 u'id': 593831840,
 u'labels': None,
 u'lastName': u'Hashim',
 u'location': u'',
 u'notes': u'',
 u'paid': u'no',
 u'phone': u'8579308953',
 u'price': u'0.00',
 u'priceSold': u'0.00',
 u'time': u'12:00pm',
 u'timezone': u'America/Toronto',
 u'type': u'Appointment with How To Manage A Small Law Firm'}